### ISSUE TITLE
Add support for trigonometric operators sin, cos, tan

### ISSUE THREAD

**Issue by WillAdams** [DSchroer/dslcad#10]
Didn't see these listed, but having support for them is pretty much essential for anything non-trivial.

**Comment by DSchroer** [comment]
Ill try to add them soon. Thanks for the feedback

**Comment by DSchroer** [comment]
These have been added in the latest pre-release. 

https://github.com/DSchroer/dslcad/releases/tag/v0.0.2-pre.3
