### ISSUE TITLE
Need better way to import multi part files

### ISSUE THREAD

**Issue by DSchroer** [DSchroer/dslcad#20]
Currently the way to bring in a multi part file as a single part is as follows:
```
reduce ./footing() as a,b:
	a ->left union(right=b);
```
This needs a cleaner way to pull it in.

**Comment by zignig** [comment]
I think the use syntax from rust to pull in symbols and modules would be very flexible and consistent.

P.s. cool project, once I get my head around the code base I will add some examples.
