### ISSUE TITLE
Crash to desktop with specific file

### ISSUE THREAD

**Issue by benthillerkus** [DSchroer/dslcad#5]
```ds
var column = circle(radius=5.0, center=true) -> shape extrude(z=10) -> shape fillet(radius=0.2);
difference(left=column, right=(column -> shape translate(x=1)));
```

**Comment by benthillerkus** [comment]
x64 Windows 10 with an NVidia GPU

**Comment by DSchroer** [comment]
So I have successfully reproduced the issue. It seems to be windows specific but also occurs under wine. Thank you for the report, I will try to get a fix out soon.

**Comment by DSchroer** [comment]
Interesting enough building a windows version locally results in it working. Seems to be something broken with the CI setup that builds the pre-built versions.

**Comment by DSchroer** [comment]
> Tbh I would have expected the culprit to be right=(...) being syntax I made up

That syntax seems fine. You can omit the `()` around it since it gets evaluated as an single argument already.

**Comment by stolksdorf** [comment]
Also getting crashes right to desktop with some files, can't seem to figure out the culprit. (x64 Windows 10 with an NVidia GPU.)

Example `gear.ds` -> Crash
Example `fidget_cube.ds` -> Works
Example `aerogrind_funnel.ds` -> Works
Example `gopro_adapter.ds` -> Crash

`cube(x=10, y=10, z=10)->shape fillet(radius=10);` -> Crash
`cube(x=10, y=10, z=10)->shape fillet(radius=9);` -> Works

**Comment by DSchroer** [comment]
@benthillerkus I did some work on the windows build pipeline. Can you try your sample on the latest pre-release? https://github.com/DSchroer/dslcad/releases/tag/v0.0.2-pre.5

On my end all of the examples work now.

**Comment by DSchroer** [comment]
You will need to adjust the code slightly. 
```
circle(radius=5.0, center=true)
```
should now be:
```
circle(radius=5.0) ->shape center()
```
